# @apibase = http://localhost:3030/api/users

###
GET http://localhost:3030/api/users

###
# POST {{apibase}}
Content-Type: application/json

{
    "username": "abdul",
    "name": "Superuser",
    "password": "mujib"
}

###
post http://localhost:3030/api/login
Content-Type: application/json

{
  "username": "abdul",
  "password": "mujib"
}