@apibase = http://localhost:3003/api/users

###
GET http://localhost:3003/api/users

###
POST {{apibase}}
Content-Type: application/json

{
    "blogs": [],
    "username": "Bidmus",
    "name": "Superuser",
    "password": "salainen"
}